require 'rbconfig'
#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html.
#
# Reads config from app's pubspec.yaml:
#   alipay_payment:
#     scheme: alipay2021000000000000  # 必填
#     ios: noutdid  # optional, 默认 utdid
#
Pod::Spec.new do |s|
  s.name             = 'alipay_payment'
  s.version          = '1.1.2'
  s.summary          = 'Flutter 支付宝支付插件'
  s.description      = <<-DESC
Flutter 支付宝支付插件，支持 iOS、Android
                       DESC
  s.homepage         = 'http://example.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.dependency 'Flutter'
  s.platform = :ios, '12.0'

  # 读取主工程 pubspec（与 alipay_kit 一致，从路径推断 app root，无需用户配置）
  root = File.dirname(__FILE__)
  calling_dir = root
  if calling_dir.include?('/ios/.symlinks')
    app_root = calling_dir.slice(0, calling_dir.index('/ios/.symlinks'))
  elsif ENV['ALIPAY_PAYMENT_APP_ROOT']
    app_root = ENV['ALIPAY_PAYMENT_APP_ROOT']
  else
    app_root = File.expand_path(File.join(Dir.pwd, '..'))
  end
  pubspec_path = File.join(app_root, 'pubspec.yaml')
  cfg = nil
  scheme = nil
  use_noutdid = false
  if File.exist?(pubspec_path)
    require 'yaml'
    cfg = YAML.load_file(pubspec_path) rescue nil
    if cfg && cfg['alipay_payment']
      scheme = cfg['alipay_payment']['scheme']&.to_s
      use_noutdid = cfg['alipay_payment']['ios'].to_s == 'noutdid'
    end
  end
  if scheme.nil? || scheme.empty?
    abort("alipay_payment: scheme 未配置。请在 pubspec.yaml 添加：\nalipay_payment:\n  scheme: alipay\${yourAppId}\n")
  end

  # 生成 Swift 配置（编译期注入，Dart 层无需传 scheme）
  config_swift = <<~SWIFT
    // Auto-generated by podspec, do not edit
    enum AlipayPaymentConfig {
      static let scheme = "#{scheme.gsub('"', '\\"')}"
    }
  SWIFT
  gen_path = File.join(root, 'Classes', 'AlipayPaymentConfig.generated.swift')
  File.write(gen_path, config_swift)

  # 写入 Info.plist（与 alipay_kit 一致：xcodeproj + plist）；用 CocoaPods 同套 Ruby，确保能 require xcodeproj
  setup_script = File.join(root, 'alipay_setup.rb')
  if File.exist?(setup_script)
    system(RbConfig.ruby, setup_script, '-s', scheme, '-a', app_root)
  end

  # AlipaySDK: utdid / noutdid
  noutdid_dir = File.join(root, 'Libraries', 'noutdid')
  lib_dir = (use_noutdid && File.directory?(noutdid_dir)) ? 'Libraries/noutdid' : 'Libraries/utdid'

  s.vendored_frameworks = "#{lib_dir}/AlipaySDK.framework"
  s.resources = "#{lib_dir}/AlipaySDK.bundle"
  s.frameworks = 'UIKit', 'Foundation', 'CoreGraphics', 'CoreText', 'QuartzCore', 'CoreTelephony', 'SystemConfiguration', 'CFNetwork', 'WebKit'
  s.libraries = 'z', 'c++'

  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386' }
  s.swift_version = '5.0'
end
